name: EventEngine
main: no.runsafe.eventengine.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Event engine
depend: [Moosic, Cheeves]
commands:
  run:
    description: Runs a script
  luaenv:
    description: Sets an Lua environment value
