name: EventEngine
main: no.runsafe.eventengine.EventEngine
version: 1.1.@BUILD@
author: Kruithne
depend: [RunsafeWorldGuardBridge]
description: Event engine
commands:
  reloadscripts:
    description: Reloads the lua engine and all scripts.